version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: musala
      MONGO_INITDB_ROOT_PASSWORD: musala

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: musala
      ME_CONFIG_MONGODB_ADMINPASSWORD: musala
      CONNECTION_STRING: mongodb://musala:musala@mongo:27017